### ISSUE TITLE
RIFF_LIST.dwSize may be incorrect

### ISSUE THREAD

**Issue by kenmux** [Ricardicus/mjpeg-avi#1]
Hello Ricardicus,

Now days I study your code, and guess the 'magic' numbers in the code. 

For [this line](https://github.com/Ricardicus/mjpeg-avi/blob/9110ae847947c67799aeb0d851e96060dceafe69/src/avi.c#L205):
`RIFF_LIST.dwSize =  150 + 12 + len + 8*nbr_of_jpgs + 8 + 4*4*nbr_of_jpgs;`

The '150' may be wrong, and should be '220'(that is, 0xDC).
Here's how I get the value:

``` bash
00000000     RIFF ( 'AVI '
0000000C             LIST ( 'hdrl'
00000010                     AVIMAINHEADER
00000058                     LIST ( 'strl'
0000005C                            AVISTREAMHEADER
00000094                            AVIBITMAPINFOHEADER
000000CC                            LIST ( 'odml'
000000D0                                   'dmlh' (
000000D8                                            NumFrames
                                                  )
                                         )
                                  )
000000DC                  )
000000E4             LIST ( 'movi' ... )
018E7320             'idx1' ( ... )
018E7968          )
```

Is it right? One more thing, what's the meaning of `char * id`?
Kindly please give some guides, thanks in advance!

**Comment by Ricardicus** [comment]
Hi kenmux!

Thank you for the inspection.

The "char * id" is an old vestige. This code was used in a different program, and the code where id was used was removed before I posted this here. I can be disregarded. In fact I might remove it. 

I studied this documentation on the AVI format: https://cdn.hackaday.io/files/274271173436768/avi.pdf .

It has been a while since I wrote it. But the line you are referring to is suppose to cover the entire 'riff' list, with the 'movi' list included. 

That is why we see the 'nbr_of_jpgs' variable. The contribution of +12, +8 and +len might compensate for this already. 

Have you tried if the AVI reader accepts the file you generate it if you edit this 'magic number' to 150?
If so, then it is very likely that it was wrong. I am sorry I cannot elaborate more on this manner. 

I remember that there was a lot of trial and error before I became correctly formatted for me.
I looked at the bytes of a 'correct' version when I edited some of these values. Honestly the documentation did not provide me with all the answers so I remember that I just accepted it after it worked.

**Comment by Ricardicus** [comment]
Hi kenmux!

Thank you for the inspection.

The "char * id" is an old vestige. This code was used in a different program, and the code where id was used was removed before I posted this here. I can be disregarded. In fact I might remove it.

I studied this documentation on the AVI format: https://cdn.hackaday.io/files/274271173436768/avi.pdf .

It has been a while since I wrote it. But the line you are referring to is suppose to cover the entire 'riff' list, with the 'movi' list included. That is why we see the 'nbr_of_jpgs' variable. The contribution of +12, +8 and +len might compensate for this already.

A list is defined as:
<pre>
typedef          struct          {
DWORD                    dwList
DWORD                    dwSize
DWORD                    dwFourCC
BYTE                              data[dwSize-4]                    //          contains          Lists          and          Chunks
}          LIST
</pre>

As you see the dwSize is supposed to be the size of the chunk it is containing, not the chunk header itself. So 220 is probably too large since it represents everything except the 'movi' list.

Have you tried if the AVI reader accepts the file you generate it if you edit this 'magic number' to 150?
If so, then maybe it was wrong. I am sorry I cannot elaborate more on why in that case.

I remember that there was a lot of trial and error before I became correctly formatted for me.
I looked at the bytes of a 'correct' version when I edited some of these values. Honestly the documentation did not provide me with all the answers so I remember that I just accepted it after it worked.

**Comment by Ricardicus** [comment]
Hi kenmux!

Thank you for the inspection.

The "char * id" is an old vestige. This code was used in a different program, and the code where id was used was removed before I posted this here. I can be disregarded. In fact I might remove it.

I studied this documentation on the AVI format: https://cdn.hackaday.io/files/274271173436768/avi.pdf .

It has been a while since I wrote it. But the line you are referring to is suppose to cover the entire 'riff' list, with the 'movi' list included. That is why we see the 'nbr_of_jpgs' variable. The contribution of +12, +8 and +len might compensate for this already.

A list is defined as:

typedef          struct          {
DWORD                    dwList
DWORD                    dwSize
DWORD                    dwFourCC
BYTE                              data[dwSize-4]                    //          contains          Lists          and          Chunks
}          LIST

As you see the dwSize is supposed to be the size of the chunk it is containing, not the chunk header itself. So 220 is probably too large since it represents everything except the 'movi' list.

Have you verified that the AVI reader accepts the file you generate it if you edit this 'magic number' to 220?

I remember that there was a lot of trial and error before I became correctly formatted for me.
I looked at the bytes of a 'correct' version when I edited some of these values. Honestly I remember the documentation was good but it did not provide me with all the answers. The AVI readers can be very picky though. I have verified that this works on VLC and Quick Time.

**Comment by Ricardicus** [comment]
Hi kenmux!

Thank you for the inspection.

The "char * id" is an old vestige. This code was used in a different program, and the code where id was used was removed before I posted this here. It can be disregarded. In fact I might remove it.

I studied this documentation on the AVI format: https://cdn.hackaday.io/files/274271173436768/avi.pdf .

It has been a while since I wrote it. But the line you are referring to is suppose to cover the entire 'riff' list, with the 'movi' list included. That is why we see the 'nbr_of_jpgs' variable. The contribution of +12, +8 and +len might compensate for this already.

A list is defined as:
<pre>
typedef struct {
DWORD dwList
DWORD dwSize
DWORD dwFourCC
BYTE data[dwSize-4] // contains Lists and Chunks
} LIST
</pre>

As you see the dwSize is supposed to be the size of the chunk it is containing, not the chunk header itself. So 220 is probably too large since it represents everything except the 'movi' list.

Have you verified that the AVI reader accepts the file you generate after you edit this 'magic number' to 220?

I remember that there was a lot of trial and error before it became correctly formatted for me.
I looked at the bytes of a 'correct' version in comparison when I edited some of these values. Honestly I remember the documentation was good but it did not provide me with all the answers. The AVI readers can be very picky though. I have verified that this works on VLC and Quick Time.

**Comment by kenmux** [comment]
Hello Ricardicus,

First of all, I'll say, I do all the tests in Windows 7, using Eclipse+CDT, and Window Media Player.

The reuslt is **YES**. The `RIFF_LIST.dwSize`,  it accepts both '150' and '220'. In fact, It accepts any value including 0. I am puzzled with this. So there's this issue.

I thought the vaule '150' is the size of all the header data that is ahead of LIST 'movi', but just could not get the value. Then I turn to this [reference](https://msdn.microsoft.com/en-us/library/windows/desktop/dd318189(v=vs.85).aspx). It describes the AVI file structure. It says:
> AVI files are identified by the FOURCC 'AVI ' in the RIFF header. All AVI files include two mandatory LIST chunks, which define the format of the streams and the stream data, respectively. An AVI file might also include an index chunk, which gives the location of the data chunks within the file.

It also says:
> The 'hdrl' list defines the format of the data and is the first required LIST chunk. The 'movi' list contains the data for the AVI sequence and is the second required LIST chunk. The 'idx1' list contains the index. 

So, in my opinion, the LIST 'hdrl' contains all the data about media format, and all headers should be its data. The value '150' in `RIFF_LIST.dwSize` should be the size from 'AVI ' to the end of LIST 'hdrl'. Am I right? What's your opinion?

Thanks for your patient replay again! The PDF file is great!
